export const emojiCards = [
	{
		imageSrc: "/assets/images/perhaps_it_will_grow_on_me.png",
		imageAlt: "emoji. skeptisk med hjerteøyne",
		emojiDescription: "Perhaps it will grow on me",
		emojiCategoryOne: "Reaksjon",
		emojiDownload: "Last ned <3",
	},
	{
		imageSrc: "/assets/images/budget_exceeded.png",
		imageAlt: "emoji. skeptisk med hjerteøyne",
		emojiDescription: "Perhaps it will grow on me",
		emojiCategoryOne: "Reaksjon",
		emojiDownload: "Last ned <3",
	},
	{
		imageSrc: "/assets/images/give_money.png",
		imageAlt: "emoji. to hender med masse pengesedler",
		emojiDescription: "Give money",
		emojiCategoryOne: "Reaksjon",
		emojiDownload: "Last ned <3",
	},
	{
		imageSrc: "/assets/images/netlife_hearteyes.png",
		imageAlt: "emoji. to grønne hjerter for øyne",
		emojiDescription: "Netlife hearteyes",
		emojiCategoryOne: "Reaksjon",
		emojiDownload: "Last ned <3",
	},
	{
		imageSrc: "/assets/images/pink_cowboy.png",
		imageAlt: "emoji. rosa cowboyhatt",
		emojiDescription: "Pink cowboy",
		emojiCategoryOne: "Ansatte",
    emojiCategoryTwo: "Penger",
		emojiDownload: "Last ned <3",
	},
	{
		imageSrc: "/assets/images/ring_tre.png",
		imageAlt: "emoji. en brun flaske",
		emojiDescription: "Ring tre",
		emojiCategoryOne: "Gjenstand",
		emojiDownload: "Last ned <3",
	},
  {
    imageSrc:"/assets/images/totally_not_crying.png",
		imageAlt:"emoji. gråter med solbriller på",
		emojiDescription:"Totally not crying",
    emojiCategoryOne:"Reaksjon",
		emojiDownload:"Last ned <3",
  },
  {
    imageSrc:"/assets/images/amz.png",
    imageAlt:"emoji. blondt hår, runde briller og svart lue",
    emojiDescription:"amz",
    emojiCategoryOne:"Ansatte",
    emojiDownload:"Last ned <3",
  },
  {
		imageSrc:"/assets/images/anders_aspaas_jr.png",
		imageAlt:"emoji. solbriller og sigg i kjeften",
		emojiDescription:"Anders Aspaas jr",
    emojiCategoryOne:"Ansatte",
		emojiDownload:"Last ned <3",
  },
  {
		imageSrc:"/assets/images/maggie.png",
		imageAlt:"emoji. biter fingre",
		emojiDescription:"Maggie",
    emojiCategoryOne:"Ansatte",
		emojiDownload:"Last ned <3",
  },
  {
		imageSrc:"/assets/images/mikes.png",
		imageAlt:"emoji. sliten utvikler",
		emojiDescription:"Mikes",
    emojiCategoryOne:"Ansatte",
		emojiDownload:"Last ned <3",
  },
]
